# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9fb68aa21cdd1d70654a7158a36aef230307f60f244fb271289cc3362065e9d0008a39eb55adb06cf7e8c455c09014e8087d074ecb8d971f8e76d255f5fc74fa

test:
  secret_key_base: c5acaaa97df4764f087f3b8543465e18dc4cf18e7a52e93439b56a1e7842af9db0c076a1e106350226673c36b04251c9cbaef36f2fd4105f8f5e230820559026

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
